baseURL = 'https://pricingtest2.netlify.app'
languageCode = 'en-us'
title = 'Pricing information | aspose.com'
theme = 'pricing'
draft = "false"

[module]
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content'
    lang = 'en'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content'
    lang = 'de'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content'
    lang = 'zh'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content'
    lang = 'ja'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content'
    lang = 'ru'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content'
    lang = 'it'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content'
    lang = 'es'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content'
    lang = 'en'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content'
    lang = 'de'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content'
    lang = 'zh'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content'
    lang = 'ja'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content'
    lang = 'ru'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content'
    lang = 'it'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content'
    lang = 'es'
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'
  

[params]
    url = "https://purchase-api.dynabic.com/v1.2/productFamily/site-aspose?isArchived=&pageNumber=&pageSize=&applyDisplayOrder=true&includeProducts=false"


[params.dynamicmenuid]
  en = "aspose-en"
  de = "aspose-de"
  zh = "aspose-zh"
  ja = "aspose-ja"
  ru = "aspose-ru"
  it = "aspose-it"
  es = "aspose-es"

defaultContentLanguage = 'en'
[languages]
  [languages.de]
    languageName = 'Deutsch'
    languageCode = "de"
    flag = "flag-de"
    weight = 4
  [languages.en]
    languageName = 'English'
    flag = "flag-us"
    languageCode = "en"
    weight = 3
  [languages.zh]
    languageName = '简体中文'
    flag = "flag-zh"
    languageCode = "zh"
    weight = 1
  [languages.ja]
    languageName = '日本語'
    flag = "flag-ja"
    languageCode = "ja"
    weight = 2
  [languages.ru]
    languageName = 'Русский'
    flag = "flag-ru"
    languageCode = "ru"
    weight = 5
  [languages.it]
    languageName = 'Italiano'
    flag = "flag-it"
    languageCode = "it"
    weight = 6
  [languages.es]
    languageName = 'Español'
    flag = "flag-es"
    languageCode = "es"
    weight = 7
